spring:
  datasource:
    url: jdbc:mysql://localhost:3306/food
    username: root
    password: 123qwezhh

# 配置mybatis-plus日志输出
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
